name: First workflows
on: push
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Print greeting
              run: echo "Hello World"
            - name: Print goodbye
              run: echo "Goodbye"
            # - uses: actions/checkout@v4
            # - uses: actions/setup-java@v4
            #   with:
            #     java-version: '17'
            #     distribution: 'oracle'
            #     cache: maven
            # - name: Build with Maven
            #   run: mvn clean install
